// FSR1 EASU functions inlined for HLSL/DXC compatibility.
//
// This header inlines only the EASU (Edge-Adaptive Spatial Upsampling) functions
// from AMD's FSR1 ffx_fsr1.h. It uses CAS's ffx_a.h for the base portability types
// (AF1, AF2, AF3, AF4, AU2, AU4, APrxLoRcpF1, etc.), which both FSR1 and CAS share.
//
// Why not just #include <ffx_fsr1.h>?
//  - FSR1's ffx_fsr1.h pulls in utility functions (FsrLfgaF, FsrSrtmF, FsrTepdDitF,
//    etc.) that reference helpers only present in FSR1's ffx_a.h (APrxMedRcpF3,
//    AGtZeroF3, AZolZeroPassF*). FSR1's ffx_a.h uses vector ternary (?:) which DXC
//    rejects ("condition for short-circuiting ternary operator must be scalar").
//  - CAS's ffx_a.h lacks those problematic functions but has everything EASU needs.
//
// The EASU code below is verbatim from FSR1 v1.0.2 ffx_fsr1.h lines 232-437,
// gated by FSR_EASU_F. Only the EASU path is needed (no RCAS, no half-precision).
//
// Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved.
// Licensed under the MIT License (see external/FidelityFX-FSR/license.txt).

#if !defined(FSR1_EASU_INLINED_H)
#define FSR1_EASU_INLINED_H

// Input callback prototypes — the including shader must implement these.
AF4 FsrEasuRF(AF2 p);
AF4 FsrEasuGF(AF2 p);
AF4 FsrEasuBF(AF2 p);

//------------------------------------------------------------------------------------------------------------------------------
// Filtering for a given tap for the scalar.
void FsrEasuTapF(
    inout AF3 aC, // Accumulated color, with negative lobe.
    inout AF1 aW, // Accumulated weight.
    AF2 off,      // Pixel offset from resolve position to tap.
    AF2 dir,      // Gradient direction.
    AF2 len,      // Length.
    AF1 lob,      // Negative lobe strength.
    AF1 clp,      // Clipping point.
    AF3 c) {      // Tap color.
    // Rotate offset by direction.
    AF2 v;
    v.x = (off.x * ( dir.x)) + (off.y * dir.y);
    v.y = (off.x * (-dir.y)) + (off.y * dir.x);
    // Anisotropy.
    v *= len;
    // Compute distance^2.
    AF1 d2 = v.x * v.x + v.y * v.y;
    // Limit to the window as at corner, 2 taps can easily be outside.
    d2 = min(d2, clp);
    // Approximation of lancos2 without sin() or rcp(), or sqrt() to get x.
    AF1 wB = AF1_(2.0/5.0) * d2 + AF1_(-1.0);
    AF1 wA = lob * d2 + AF1_(-1.0);
    wB *= wB;
    wA *= wA;
    wB = AF1_(25.0/16.0) * wB + AF1_(-(25.0/16.0 - 1.0));
    AF1 w = wB * wA;
    // Do weighted average.
    aC += c * w; aW += w;
}

//------------------------------------------------------------------------------------------------------------------------------
// Accumulate direction and length.
void FsrEasuSetF(
    inout AF2 dir,
    inout AF1 len,
    AF2 pp,
    AP1 biS, AP1 biT, AP1 biU, AP1 biV,
    AF1 lA, AF1 lB, AF1 lC, AF1 lD, AF1 lE) {
    AF1 w = AF1_(0.0);
    if (biS) w = (AF1_(1.0) - pp.x) * (AF1_(1.0) - pp.y);
    if (biT) w =            pp.x  * (AF1_(1.0) - pp.y);
    if (biU) w = (AF1_(1.0) - pp.x) *            pp.y ;
    if (biV) w =            pp.x  *            pp.y ;
    AF1 dc = lD - lC;
    AF1 cb = lC - lB;
    AF1 lenX = max(abs(dc), abs(cb));
    lenX = APrxLoRcpF1(lenX);
    AF1 dirX = lD - lB;
    dir.x += dirX * w;
    lenX = ASatF1(abs(dirX) * lenX);
    lenX *= lenX;
    len += lenX * w;
    AF1 ec = lE - lC;
    AF1 ca = lC - lA;
    AF1 lenY = max(abs(ec), abs(ca));
    lenY = APrxLoRcpF1(lenY);
    AF1 dirY = lE - lA;
    dir.y += dirY * w;
    lenY = ASatF1(abs(dirY) * lenY);
    lenY *= lenY;
    len += lenY * w;
}

//------------------------------------------------------------------------------------------------------------------------------
void FsrEasuF(
    out AF3 pix,
    AU2 ip,  // Integer pixel position in output.
    AU4 con0, // Constants generated by FsrEasuCon().
    AU4 con1,
    AU4 con2,
    AU4 con3) {
    // Get position of 'f'.
    AF2 pp = AF2(ip) * AF2_AU2(con0.xy) + AF2_AU2(con0.zw);
    AF2 fp = floor(pp);
    pp -= fp;

    AF2 p0 = fp * AF2_AU2(con1.xy) + AF2_AU2(con1.zw);
    AF2 p1 = p0 + AF2_AU2(con2.xy);
    AF2 p2 = p0 + AF2_AU2(con2.zw);
    AF2 p3 = p0 + AF2_AU2(con3.xy);
    AF4 bczzR = FsrEasuRF(p0);
    AF4 bczzG = FsrEasuGF(p0);
    AF4 bczzB = FsrEasuBF(p0);
    AF4 ijfeR = FsrEasuRF(p1);
    AF4 ijfeG = FsrEasuGF(p1);
    AF4 ijfeB = FsrEasuBF(p1);
    AF4 klhgR = FsrEasuRF(p2);
    AF4 klhgG = FsrEasuGF(p2);
    AF4 klhgB = FsrEasuBF(p2);
    AF4 zzonR = FsrEasuRF(p3);
    AF4 zzonG = FsrEasuGF(p3);
    AF4 zzonB = FsrEasuBF(p3);

    AF4 bczzL = bczzB * AF4_(0.5) + (bczzR * AF4_(0.5) + bczzG);
    AF4 ijfeL = ijfeB * AF4_(0.5) + (ijfeR * AF4_(0.5) + ijfeG);
    AF4 klhgL = klhgB * AF4_(0.5) + (klhgR * AF4_(0.5) + klhgG);
    AF4 zzonL = zzonB * AF4_(0.5) + (zzonR * AF4_(0.5) + zzonG);
    AF1 bL = bczzL.x;
    AF1 cL = bczzL.y;
    AF1 iL = ijfeL.x;
    AF1 jL = ijfeL.y;
    AF1 fL = ijfeL.z;
    AF1 eL = ijfeL.w;
    AF1 kL = klhgL.x;
    AF1 lL = klhgL.y;
    AF1 hL = klhgL.z;
    AF1 gL = klhgL.w;
    AF1 oL = zzonL.z;
    AF1 nL = zzonL.w;
    AF2 dir = AF2_(0.0);
    AF1 len = AF1_(0.0);
    FsrEasuSetF(dir, len, pp, true,  false, false, false, bL, eL, fL, gL, jL);
    FsrEasuSetF(dir, len, pp, false, true,  false, false, cL, fL, gL, hL, kL);
    FsrEasuSetF(dir, len, pp, false, false, true,  false, fL, iL, jL, kL, nL);
    FsrEasuSetF(dir, len, pp, false, false, false, true,  gL, jL, kL, lL, oL);

    AF2 dir2 = dir * dir;
    AF1 dirR = dir2.x + dir2.y;
    AP1 zro = dirR < AF1_(1.0/32768.0);
    dirR = APrxLoRsqF1(dirR);
    dirR = zro ? AF1_(1.0) : dirR;
    dir.x = zro ? AF1_(1.0) : dir.x;
    dir *= AF2_(dirR);
    len = len * AF1_(0.5);
    len *= len;
    AF1 stretch = (dir.x * dir.x + dir.y * dir.y) * APrxLoRcpF1(max(abs(dir.x), abs(dir.y)));
    AF2 len2 = AF2(AF1_(1.0) + (stretch - AF1_(1.0)) * len, AF1_(1.0) + AF1_(-0.5) * len);
    AF1 lob = AF1_(0.5) + AF1_((1.0/4.0 - 0.04) - 0.5) * len;
    AF1 clp = APrxLoRcpF1(lob);

    AF3 min4 = min(AMin3F3(AF3(ijfeR.z, ijfeG.z, ijfeB.z), AF3(klhgR.w, klhgG.w, klhgB.w), AF3(ijfeR.y, ijfeG.y, ijfeB.y)),
                   AF3(klhgR.x, klhgG.x, klhgB.x));
    AF3 max4 = max(AMax3F3(AF3(ijfeR.z, ijfeG.z, ijfeB.z), AF3(klhgR.w, klhgG.w, klhgB.w), AF3(ijfeR.y, ijfeG.y, ijfeB.y)),
                   AF3(klhgR.x, klhgG.x, klhgB.x));
    AF3 aC = AF3_(0.0);
    AF1 aW = AF1_(0.0);
    FsrEasuTapF(aC, aW, AF2( 0.0, -1.0) - pp, dir, len2, lob, clp, AF3(bczzR.x, bczzG.x, bczzB.x)); // b
    FsrEasuTapF(aC, aW, AF2( 1.0, -1.0) - pp, dir, len2, lob, clp, AF3(bczzR.y, bczzG.y, bczzB.y)); // c
    FsrEasuTapF(aC, aW, AF2(-1.0,  1.0) - pp, dir, len2, lob, clp, AF3(ijfeR.x, ijfeG.x, ijfeB.x)); // i
    FsrEasuTapF(aC, aW, AF2( 0.0,  1.0) - pp, dir, len2, lob, clp, AF3(ijfeR.y, ijfeG.y, ijfeB.y)); // j
    FsrEasuTapF(aC, aW, AF2( 0.0,  0.0) - pp, dir, len2, lob, clp, AF3(ijfeR.z, ijfeG.z, ijfeB.z)); // f
    FsrEasuTapF(aC, aW, AF2(-1.0,  0.0) - pp, dir, len2, lob, clp, AF3(ijfeR.w, ijfeG.w, ijfeB.w)); // e
    FsrEasuTapF(aC, aW, AF2( 1.0,  1.0) - pp, dir, len2, lob, clp, AF3(klhgR.x, klhgG.x, klhgB.x)); // k
    FsrEasuTapF(aC, aW, AF2( 2.0,  1.0) - pp, dir, len2, lob, clp, AF3(klhgR.y, klhgG.y, klhgB.y)); // l
    FsrEasuTapF(aC, aW, AF2( 2.0,  0.0) - pp, dir, len2, lob, clp, AF3(klhgR.z, klhgG.z, klhgB.z)); // h
    FsrEasuTapF(aC, aW, AF2( 1.0,  0.0) - pp, dir, len2, lob, clp, AF3(klhgR.w, klhgG.w, klhgB.w)); // g
    FsrEasuTapF(aC, aW, AF2( 1.0,  2.0) - pp, dir, len2, lob, clp, AF3(zzonR.z, zzonG.z, zzonB.z)); // o
    FsrEasuTapF(aC, aW, AF2( 0.0,  2.0) - pp, dir, len2, lob, clp, AF3(zzonR.w, zzonG.w, zzonB.w)); // n
    // Normalize and dering.
    pix = min(max4, max(min4, aC * AF3_(ARcpF1(aW))));
}

#endif // FSR1_EASU_INLINED_H
